name: "pr-auto-labeler"
on:
- pull_request_target

jobs:
  apply_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: release-drafter/release-drafter@v5
      with:
        name: v${{ github.event.inputs.tag }}
        tag: temp-tag-created-by-pr-auto-labeler
        version: ${{ github.event.inputs.tag }}
        publish: false
        config-name: label-pr-config.yml
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # GitHub CLI available on all GitHub runners; delete draft release with auto-confirmation flag
    - run: gh release delete temp-tag-created-by-pr-auto-labeler -y
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}